/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'eddyCurrentTesting' : IDL.Null,
  'radiologicalTesting' : IDL.Null,
  'magnaFluxTesting' : IDL.Null,
  'ultrasonicTesting' : IDL.Null,
  'generalInquiry' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : ServiceType,
  'message' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'useCases' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'shortDescription' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'detailedDescription' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getServiceById' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getTestimonialById' : IDL.Func([IDL.Nat], [IDL.Opt(Testimonial)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'eddyCurrentTesting' : IDL.Null,
    'radiologicalTesting' : IDL.Null,
    'magnaFluxTesting' : IDL.Null,
    'ultrasonicTesting' : IDL.Null,
    'generalInquiry' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : ServiceType,
    'message' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'useCases' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'shortDescription' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'detailedDescription' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getServiceById' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getTestimonialById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Testimonial)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };