/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'name' : string,
  'email' : string,
  'serviceInterest' : ServiceType,
  'message' : string,
  'timestamp' : Time,
  'companyName' : string,
  'phone' : string,
}
export interface Service {
  'id' : bigint,
  'useCases' : Array<string>,
  'name' : string,
  'shortDescription' : string,
  'benefits' : Array<string>,
  'detailedDescription' : string,
}
export type ServiceType = { 'eddyCurrentTesting' : null } |
  { 'radiologicalTesting' : null } |
  { 'magnaFluxTesting' : null } |
  { 'ultrasonicTesting' : null } |
  { 'generalInquiry' : null };
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'company' : string,
  'message' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getServiceById' : ActorMethod<[bigint], [] | [Service]>,
  'getTestimonialById' : ActorMethod<[bigint], [] | [Testimonial]>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, ServiceType, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];